name: fetch-blogs-from-medium
run-name: Scrapping Pranshu's Medium blog
on:
  schedule:
    - cron: "30 0 * * *" # run script at 6.00 am IST
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "Pranshu1902/Portfolio"
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: install dependencies
        run: python -m pip install -r .github/requirements.txt
      - name: execute py script # run the run.py to get the latest data
        run: |
          python ./.github/mediumBlogsFetch.py
      - name: switching from HTTPS to SSH
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "üåç Update JSON- srap blogs from medium"
      - name: fetch from master
        run: git fetch origin master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
